// <auto-generated />
namespace WebApplication7.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updatesocialmediatable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatesocialmediatable));
        
        string IMigrationMetadata.Id
        {
            get { return "202103310706317_updatesocialmediatable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
